version: '3'

services:
  email-microservice:
    image: springboot-docker-compose-app:1
    build:
      context: email
      dockerfile: Dockerfile
    volumes:
      - /email
    restart: always
    ports:
      - 8000:8000
    networks:
      - compose-network

  postgres-database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432
    networks:
      - compose-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - compose-network   

networks: 
  compose-network:
    driver: bridge